name: Deploy Dev to Main /dev/

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout development branch
        uses: actions/checkout@v3
        with:
          ref: development

      - name: Clone main branch into temp folder
        run: |
          git clone --branch main https://github.com/${{ github.repository }} temp-clone

      - name: Copy dev branch files into temp-clone/dev
        run: |
          # Remove existing dev folder in temp clone
          rm -rf temp-clone/dev
          mkdir -p temp-clone/dev
          # Enable extended globbing for exclude pattern
          shopt -s extglob
          # Copy everything except .git, .github, dev folder, and temp-clone itself
          cp -r !(temp-clone|.git|.github|dev) temp-clone/dev/

      - name: Commit and push changes to main branch
        run: |
          cd temp-clone
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dev
          # Commit only if there are changes, otherwise print message
          git commit -m "Deploy dev branch to /dev/ on main [skip ci]" || echo "No changes to commit"
          git push origin main